"""Initial

Revision ID: d916478479c2
Revises: 
Create Date: 2022-09-10 11:52:56.432372

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd916478479c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'history',
        sa.Column('uid', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('update_date', sa.DateTime(), nullable=False),
        sa.UniqueConstraint('uid', 'update_date', name='uix_obj_history_change')
    )
    op.create_table(
        'relations',
        sa.Column('relationId', sa.String(), nullable=False),
        sa.Column('childrenId', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('relationId', 'childrenId', name=op.f('pk__relations')),
        sa.UniqueConstraint('relationId', 'childrenId', name='uix_pair_children_parent')
    )
    op.create_table(
        'units',
        sa.Column('uid', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('type', sa.Enum('folder', 'file', name='type'), nullable=False),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('parentId', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('uid', name=op.f('pk__units'))
    )
    op.create_index(op.f('ix__units__url'), 'units', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__units__url'), table_name='units')
    op.drop_table('units')
    op.drop_table('relations')
    op.drop_table('history')
    # ### end Alembic commands ###
