"""Initial

Revision ID: fc46527daf61
Revises: 
Create Date: 2022-09-10 14:49:59.442346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc46527daf61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.UniqueConstraint('uid', 'update_date', name='uix_obj_history_change')
    )
    op.create_table('relations',
    sa.Column('relation_id', sa.String(), nullable=False),
    sa.Column('children_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('relation_id', 'children_id', name=op.f('pk__relations')),
    sa.UniqueConstraint('relation_id', 'children_id', name='uix_pair_children_parent')
    )
    op.create_table('units',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('file', 'folder', name='type'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__units'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    op.drop_table('relations')
    op.drop_table('history')
    # ### end Alembic commands ###
